id: stream1
uri: rtsp://streaming-server:8554/video-stream
reconnect_backoff_time: 1
max_fps: 10
jpeg_encode: True
log_level: INFO
camera_position_source:
  stream_id: "positionsource:self"
redis:
  host: redis
  port: 6379